/*
 * generated by Xtext 2.25.0
 */
package hu.haizu.cogni.hypergraph.tests

import com.google.inject.Inject
import hu.haizu.cogni.hypergraph.model.basicbuild.HyperGraphMultiSet
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(HypergraphDslInjectorProvider)
class HypergraphDslParsingTest {
	@Inject
	ParseHelper<HyperGraphMultiSet> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
