/*
 * generated by Xtext 2.25.0
 */
package hu.haizu.cogni.hypergraph.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class HypergraphDslProposalProvider extends AbstractHypergraphDslProposalProvider {
}
